[options]
addons_path = /mnt/extra-addons
data_dir    = /var/lib/odoo

db_host     = db_qs
db_port     = 5432
db_user     = odoo
db_password = password

admin_passwd = admin123
# db_name = odoo18_qs   ; (optional festpinnen nach der Initialisierung)
