[options]
; Wo Odoo die Addons sucht (lokal mountbar)
addons_path = /mnt/extra-addons
; Filestore
data_dir    = /var/lib/odoo

; Postgres-Zugang
db_host     = db
db_port     = 5432
db_user     = odoo
db_password = password

; Master-Passwort für DB-Verwaltung (z. B. UI /web/database/manager)
admin_passwd = admin123

; optional: wenn du nach der Initialisierung auf eine feste DB pinnen willst:
; db_name = odoo_dev

; optional: dbfilter steuern, leer = alle
; dbfilter = .*
